name: 'Verify Hashes'
description: 'Verify hash files like <file>.sha256 from GitHub Actions'
author: 'Sam Gammon'

branding:
  icon: 'check'
  color: 'green'

inputs:
  paths:
    description: 'Paths'
    required: false
    default: '.'
  strict:
    description: 'Strict Verification'
    required: false
    default: 'false'
  ignored:
    description: 'Ignored Paths'
    required: false
    default: |
      node_modules/
  globs:
    description: 'Paths are Globs'
    required: false
    default: 'true'
  warn-only:
    description: 'Only Warn, Never Fail'
    required: false
    default: 'false'

outputs:
  files-checked-count:
    description: 'Count of hash files which were checked by the action'
  files-verified-count:
    description: 'Count of hash files which were verified'
  files-failed-count:
    description: 'Count of hash files which failed checks'

runs:
  using: node20
  main: dist/action.js
