name: 'Check: ESLint'

on:
  workflow_call: {}

permissions:
  contents: read

jobs:
  check-eslint:
    name: 'Check: ESLint'
    runs-on: ubuntu-latest
    permissions:
      security-events: write
    steps:
      - name: 'Setup: Harden Runner'
        uses: step-security/harden-runner@91182cccc01eb5e619899d80e4e971d6181294a7 # v2.10.1
        with:
          disable-sudo: true
          egress-policy: block
          allowed-endpoints: >
            api.github.com:443
            bun.sh:443
            github.com:443
            objects.githubusercontent.com:443
            registry.npmjs.org:443
      - name: 'Setup: Checkout'
        id: checkout
        uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4.2.0
        with:
          persist-credentials: false
      - name: 'Setup: Node'
        uses: actions/setup-node@0a44ba7841725637a19e28fa30b79a866c81b0a6 # v4.0.4
        with:
          node-version-file: .node-version
      - name: 'Setup: Bun'
        uses: oven-sh/setup-bun@4bc047ad259df6fc24a6c9b0f9a0cb08cf17fbe5 # v2.0.1
        with:
          bun-version: latest
      - name: 'Setup: PNPM'
        uses: pnpm/action-setup@a3252b78c470c02df07e9d59298aecedc3ccdd6d # v3.0.0
        with:
          version: '8.15.3'
          run_install: |
            - args: [--frozen-lockfile, --strict-peer-dependencies]
      - name: 'Build: Bundle'
        id: build-bundle
        run: bun --bun run build
      - name: 'Check: Run ESLint'
        run: |
          bun run lint -- --format @microsoft/eslint-formatter-sarif --output-file eslint-results.sarif
        continue-on-error: true
      - name: 'Analysis: SARIF'
        uses: github/codeql-action/upload-sarif@e2b3eafc8d227b0241d48be5f425d47c2d750a13 # v3.26.10
        with:
          sarif_file: eslint-results.sarif
          wait-for-processing: true
