name: 'Check: Dependency Review'

on:
  workflow_call: {}

permissions:
  contents: read

jobs:
  dependency-review:
    name: 'Check: Dependency Review'
    runs-on: ubuntu-latest
    steps:
      - name: 'Setup: Harden Runner'
        uses: step-security/harden-runner@63c24ba6bd7ba022e95695ff85de572c04a18142 # v2.7.0
        with:
          egress-policy: audit
      - name: 'Setup: Checkout'
        uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 # v4.1.2
        with:
          persist-credentials: false
      - name: 'Dependency Review'
        uses: actions/dependency-review-action@0fa40c3c10055986a88de3baa0d6ec17c5a894b3 # v4.2.3
