name: 'Check: Dependency Review'

on:
  workflow_call: {}

permissions:
  contents: read

jobs:
  dependency-review:
    name: 'Check: Dependency Review'
    runs-on: ubuntu-latest
    steps:
      - name: 'Setup: Harden Runner'
        uses: step-security/harden-runner@17d0e2bd7d51742c71671bd19fa12bdc9d40a3d6 # v2.8.1
        with:
          disable-sudo: true
          egress-policy: block
          allowed-endpoints: >
            api.deps.dev:443
            api.github.com:443
            api.securityscorecards.dev:443
            github.com:443
      - name: 'Setup: Checkout'
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
        with:
          persist-credentials: false
      - name: 'Dependency Review'
        uses: actions/dependency-review-action@5a2ce3f5b92ee19cbb1541a4984c76d921601d7c # v4.3.4
