name: 'Check: ESLint'

on:
  workflow_call: {}

permissions:
  contents: read

jobs:
  check-eslint:
    name: 'Check: ESLint'
    runs-on: ubuntu-latest
    permissions:
      security-events: write
    steps:
      - name: 'Setup: Harden Runner'
        uses: step-security/harden-runner@63c24ba6bd7ba022e95695ff85de572c04a18142 # v2.7.0
        with:
          egress-policy: audit
      - name: 'Setup: Checkout'
        id: checkout
        uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 # v4.1.2
        with:
          persist-credentials: false
      - name: 'Setup: Node'
        uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4.0.2
        with:
          node-version-file: .node-version
      - name: 'Setup: Bun'
        uses: oven-sh/setup-bun@d3603274aca5625baad52ec06108517a089cdd00 # v1.2.0
        with:
          bun-version: latest
      - name: 'Setup: PNPM'
        uses: pnpm/action-setup@a3252b78c470c02df07e9d59298aecedc3ccdd6d # v3.0.0
        with:
          version: '8.15.3'
          run_install: |
            - args: [--frozen-lockfile, --strict-peer-dependencies]
      - name: 'Check: Run ESLint'
        run: |
          bun run lint -- --format @microsoft/eslint-formatter-sarif --output-file eslint-results.sarif
        continue-on-error: true
      - name: 'Analysis: SARIF'
        uses: github/codeql-action/upload-sarif@05963f47d870e2cb19a537396c1f668a348c7d8f # v3.24.8
        with:
          sarif_file: eslint-results.sarif
          wait-for-processing: true
