name: 'Build & Test'

on:
  workflow_call: {}

permissions:
  contents: read

jobs:
  test-typescript:
    name: 'Tests: Unit'
    runs-on: ubuntu-latest

    steps:
      - name: 'Setup: Harden Runner'
        uses: step-security/harden-runner@63c24ba6bd7ba022e95695ff85de572c04a18142 # v2.7.0
        with:
          egress-policy: audit
      - name: 'Setup: Checkout'
        id: checkout
        uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 # v4.1.2
        with:
          persist-credentials: false
      - name: 'Setup: Node'
        uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4.0.2
        with:
          node-version-file: .node-version
      - name: 'Setup: Bun'
        uses: oven-sh/setup-bun@d3603274aca5625baad52ec06108517a089cdd00 # v1.2.0
        with:
          bun-version: latest
      - name: 'Setup: PNPM'
        uses: pnpm/action-setup@a3252b78c470c02df07e9d59298aecedc3ccdd6d # v3.0.0
        with:
          version: '8.15.3'
          run_install: |
            - args: [--frozen-lockfile, --strict-peer-dependencies]
      - name: 'Build: Bundle'
        id: build-bundle
        run: bun --bun run build
      - name: 'Check: Formatting'
        id: npm-format-check
        run: bun run format:check
      - name: 'Check: Test'
        id: npm-ci-test
        run: bun run ci-test
      - name: 'Reporting: Code Coverage'
        uses: codecov/codecov-action@54bcd8715eee62d40e33596ef5e8f0f48dbbccab # v4.1.0
        continue-on-error: true
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
      - name: 'Artifact: Distribution'
        uses: actions/upload-artifact@5d5d22a31266ced268874388b861e4b58bb5c2f3 # v4.3.1
        with:
          name: hashlock-dist-${{ github.sha }}
          retention-days: 7
          compression-level: 8
          overwrite: true
          path: dist/*

  test-action:
    name: 'Tests: Action'
    runs-on: ubuntu-latest

    steps:
      - name: 'Setup: Harden Runner'
        uses: step-security/harden-runner@63c24ba6bd7ba022e95695ff85de572c04a18142 # v2.7.0
        with:
          egress-policy: audit
      - name: 'Setup: Checkout'
        id: checkout
        uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 # v4.1.2
      - name: 'Test: Local Action'
        id: test-action
        uses: ./

  test-action-strict:
    name: 'Tests: Action (Strict)'
    runs-on: ubuntu-latest

    steps:
      - name: 'Setup: Harden Runner'
        uses: step-security/harden-runner@63c24ba6bd7ba022e95695ff85de572c04a18142 # v2.7.0
        with:
          egress-policy: audit
      - name: 'Setup: Checkout'
        id: checkout
        uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 # v4.1.2
      - name: 'Test: Local Action'
        id: test-action
        uses: ./
        with:
          strict: true
