name: 'Build & Test'

on:
  workflow_call: {}

permissions:
  contents: read

jobs:
  test-typescript:
    name: 'Tests: Unit'
    runs-on: ubuntu-latest

    steps:
      - name: 'Setup: Harden Runner'
        uses: step-security/harden-runner@cb605e52c26070c328afc4562f0b4ada7618a84e # v2.10.4
        with:
          disable-sudo: true
          egress-policy: block
          allowed-endpoints: >
            api.codecov.io:443
            api.github.com:443
            bun.sh:443
            cli.codecov.io:443
            github.com:443
            objects.githubusercontent.com:443
            registry.npmjs.org:443
      - name: 'Setup: Checkout'
        id: checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false
      - name: 'Setup: Node'
        uses: actions/setup-node@1d0ff469b7ec7b3cb9d8673fde0c81c44821de2a # v4.2.0
        with:
          node-version-file: .node-version
      - name: 'Setup: Bun'
        uses: oven-sh/setup-bun@4bc047ad259df6fc24a6c9b0f9a0cb08cf17fbe5 # v2.0.1
        with:
          bun-version: latest
      - name: 'Setup: PNPM'
        uses: pnpm/action-setup@a3252b78c470c02df07e9d59298aecedc3ccdd6d # v3.0.0
        with:
          version: '8.15.3'
          run_install: |
            - args: [--frozen-lockfile, --strict-peer-dependencies]
      - name: 'Build: Bundle'
        id: build-bundle
        run: bun --bun run build
      - name: 'Check: Formatting'
        id: npm-format-check
        run: bun run format:check
      - name: 'Check: Test'
        id: npm-ci-test
        run: bun run ci-test
      - name: 'Reporting: Code Coverage'
        uses: codecov/codecov-action@b9fd7d16f6d7d1b5d2bec1a2887e65ceed900238 # v4.6.0
        continue-on-error: true
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
      - name: 'Artifact: Distribution'
        uses: actions/upload-artifact@65c4c4a1ddee5b72f698fdd19549f0f0fb45cf08 # v4.6.0
        with:
          name: hashlock-dist-${{ github.sha }}
          retention-days: 7
          compression-level: 8
          overwrite: true
          path: dist/*

  test-action:
    name: 'Tests: Action'
    runs-on: ubuntu-latest

    steps:
      - name: 'Setup: Harden Runner'
        uses: step-security/harden-runner@cb605e52c26070c328afc4562f0b4ada7618a84e # v2.10.4
        with:
          disable-sudo: true
          egress-policy: block
          allowed-endpoints: >
            github.com:443
      - name: 'Setup: Checkout'
        id: checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: 'Test: Local Action'
        id: test-action
        uses: ./

  test-action-strict:
    name: 'Tests: Action (Strict)'
    runs-on: ubuntu-latest

    steps:
      - name: 'Setup: Harden Runner'
        uses: step-security/harden-runner@cb605e52c26070c328afc4562f0b4ada7618a84e # v2.10.4
        with:
          disable-sudo: true
          egress-policy: block
          allowed-endpoints: >
            github.com:443
      - name: 'Setup: Checkout'
        id: checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: 'Test: Local Action'
        id: test-action
        uses: ./
        with:
          strict: true
