name: 'Native Builds'

on:
  workflow_call:
    inputs:
      artifact-prefix:
        description: 'Artifact Prefix'
        type: string
        default: 'hashlock-dev'
      retention-days:
        description: 'Artifact Retention'
        type: number
        default: 7

  workflow_dispatch:
    inputs:
      artifact-prefix:
        description: 'Artifact Prefix'
        type: string
        default: 'hashlock'
      retention-days:
        description: 'Artifact Retention'
        type: number
        default: 7

permissions:
  contents: read

jobs:
  native-build:
    name: 'Native'
    uses: ./.github/workflows/ci.native-build.yml
    permissions:
      actions: read
      contents: read
      id-token: write
    strategy:
      fail-fast: false
      matrix:
        platform: [linux-amd64, macos-amd64, macos-aarch64]
        include:
          ## Linux: AMD64
          - platform: linux-amd64
            label: 'Linux x86-64'
            runner: ubuntu-latest

          ## macOS: AMD64
          - platform: macos-amd64
            label: 'macOS x86-64'
            runner: macos-latest

          ## macOS: M-series
          - platform: macos-aarch64
            label: 'macOS aarch64'
            runner: macos-13-xlarge

    with:
      label: ${{ matrix.label }}
      runner: ${{ matrix.runner }}
      tag: ${{ matrix.platform }}
      artifact: '${{ inputs.artifact-prefix }}.${{ matrix.platform }}'
      retention-days: ${{ inputs.retention-days }}

  prepare-artifacts:
    name: 'Executables'
    runs-on: ubuntu-latest
    needs: [native-build]
    outputs:
      hashes: ${{ steps.hash.outputs.hashes }}
    steps:
      - name: 'Download: Artifacts'
        uses: actions/download-artifact@8caf195ad4b1dee92908e23f56eeb0696f1dd42d # v4.1.5
        with:
          path: ${{ inputs.artifact-prefix }}
          pattern: '${{ inputs.artifact-prefix }}*'
          merge-multiple: true
      - name: 'Build: Provenance Hashes'
        shell: bash
        id: hash
        run: |
          echo "Release assets:"
          cd ${{ inputs.artifact-prefix }}/
          ls -la ./
          file ./*
          du -h ./*
          echo ""

          sha256sum ./* > ../pkg-hashes.txt
          echo "Hashes:"
          cat ../pkg-hashes.txt
          echo ""

          cat ../pkg-hashes.txt | base64 -w0 > ../pkg-hashes-encoded.txt
          echo "Encoded Hashes:"
          cat ../pkg-hashes-encoded.txt
          echo ""

          echo "hashes=$(sha256sum ./* | base64 -w0)" >> "$GITHUB_OUTPUT"
          cd ..
      - name: 'Artifact: Merged'
        uses: actions/upload-artifact@5d5d22a31266ced268874388b861e4b58bb5c2f3 # v4.3.1
        with:
          name: ${{ inputs.artifact-prefix }}-all
          retention-days: ${{ inputs.retention-days }}
          compression-level: 4
          overwrite: true
          path: '${{ inputs.artifact-prefix }}/*'

  provenance:
    name: 'SLSA Provenance'
    needs: [native-build, prepare-artifacts]
    uses: slsa-framework/slsa-github-generator/.github/workflows/generator_generic_slsa3.yml@v1.10.0
    permissions:
      actions: read
      contents: write
      id-token: write
    with:
      base64-subjects: '${{ needs.prepare-artifacts.outputs.hashes }}'
      upload-assets: false
