name: 'PR'

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  build-test:
    name: 'Build & Test'
    uses: ./.github/workflows/ci.build-test.yml
    secrets: inherit

  check-dist:
    name: 'Checks'
    uses: ./.github/workflows/check.dist.yml

  check-eslint:
    name: 'Checks'
    uses: ./.github/workflows/check.eslint.yml

  check-dependencies:
    name: 'Checks'
    uses: ./.github/workflows/check.dependency-review.yml

  check-codeql:
    name: 'Checks'
    uses: ./.github/workflows/check.codeql-analysis.yml
    permissions:
      actions: read
      checks: write
      contents: read
      security-events: write
